using System;
using System.Collections.Generic;
using System.IO;


namespace JSONval {

	using Newtonsoft.Json;
	using Newtonsoft.Json.Linq;
	using Newtonsoft.Json.Schema;
	using Newtonsoft.Json.Schema.Generation;


	/// <summary>
	/// TEST CLASS - generated by import via "Paste Special..."
	/// </summary>
	public class Rootobject {
		public string schema { get; set; }
		public string type { get; set; }
		public Properties properties { get; set; }
		public bool additionalProperties { get; set; }
		public string[] required { get; set; }
	}

	public class Properties {
		public TrainDeviceTree traindevicetree { get; set; }
	}

	public class TrainDeviceTree {
		public string type { get; set; }
		public Properties1 properties { get; set; }
		public bool additionalProperties { get; set; }
		public string[] required { get; set; }
	}

	public class Properties1 {
		public TrainUic trainuic { get; set; }
		public SiemensTrainNumber siemenstrainnumber { get; set; }
	}

	public class TrainUic {
		public string type { get; set; }
	}

	public class SiemensTrainNumber {
		public string type { get; set; }
	}



	/// <summary>
	/// JsonValidator - reading and generating tests
	/// </summary>

	internal class JsonValidator {
		private readonly string _jsonFile = null;
		private readonly string _schemaFile = null;

		private const string DummySchema = @"{'$schema': 'https://json-schema.org/draft/2019-09/schema'}";

		private StreamReader streamreader = null;
		private JsonTextReader textreader = null;

		private int Age { get; set; }

		/// <summary>
		/// ctor
		/// </summary>
		/// <param name="args"></param>
		public JsonValidator(IReadOnlyList<string> args) {
			_jsonFile = args[0];
			_schemaFile = (args.Count > 1) ? args[1] : DummySchema; // ignore the rest, if any
		}


		/// <summary>
		/// dtor
		/// </summary>
		~JsonValidator() {
			textreader?.Close();
		}


		/// <summary>
		/// get JSON schema
		/// </summary>
		private JSchema JsonSchema {
			get {
				if (_schemaFile.Equals(DummySchema))
					return JSchema.Parse(_schemaFile);

				using (streamreader = File.OpenText(_schemaFile))
					try {
						textreader = new JsonTextReader(streamreader) {
							CloseInput = true
						};
						
						JSchema schema = JSchema.Load(textreader, new JSchemaReaderSettings() {
							ValidateVersion = true,
							ResolveSchemaReferences = true
						});

						// try to generate Schema from class
						TrainDeviceTree tdt = new TrainDeviceTree();
						JSchemaGenerator generator = new JSchemaGenerator();
						
						schema = generator.Generate(tdt.GetType());

						return schema;
					}
					catch (JsonReaderException error) {
						Console.WriteLine(error);
						return null;
					}
			}
		}


		/// <summary>
		/// get JSON file
		/// </summary>
		private JToken JsonFile {
			get {
				using (streamreader = File.OpenText(_jsonFile))
					try {
						textreader = new JsonTextReader(streamreader) {
							CloseInput = true
						};

						JToken json = JToken.Load(textreader, new JsonLoadSettings() {
							DuplicatePropertyNameHandling = DuplicatePropertyNameHandling.Error,
							CommentHandling = CommentHandling.Ignore,
							LineInfoHandling = LineInfoHandling.Ignore
						});

						return json;
					}
					catch (JsonReaderException error) {
						Console.WriteLine(error);
						return null;
					}
			}
		}


		/// <summary>
		/// validate JSON file against JSON schema
		/// </summary>
		public bool JsonFileIsValid {
			get {
				try {
					bool valid = JsonFile.IsValid(JsonSchema, out IList<ValidationError> messages);
					Messages = messages;
					return valid;
				}
				catch (Exception error) {
					Age = 4711;
					Console.WriteLine($"{error} has some {Age}");
				}
				return false;
			}
		}


		public IList<ValidationError> Messages {
			get;
			private set;
		}
	}


	public static class Start {
		/// <summary>
		/// args[0] = .json file (mandatory)
		/// args[1] = schema file (optional)
		/// </summary>
		/// <param name="args"></param>
		private static void Main(string[] args) {
			if (args.Length == 0) {
				Console.WriteLine("No .json file available!");
			}
			else {
				JsonValidator jsonVal = new JsonValidator(args);
				Console.WriteLine("Validation results:");
				Console.WriteLine("Validation was {0}.", jsonVal.JsonFileIsValid.ToString().ToLower());
				Console.WriteLine(jsonVal.Messages != null ? jsonVal.Messages.ToString() : "No schema errors.");
			}
		}
	}
}